import { BlockType, type ContentBlueprintDefinition } from "../../../types";

export const editorialPublicationBlueprints = [
  {
    id: "editorial-publication.home",
    patternId: "editorial-publication.home",
    name: "Publication homepage",
    description: "Lead with a defining story and make the latest editorial work easy to discover.",
    outcome: "Editorial lead, recent stories, topic discovery, and newsletter CTA.",
    subject: "page",
    category: "home",
    source: "pack",
    packId: "editorial-publication",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "Independent stories",
          title: "Go further than the usual guide",
          subtitle: "First-hand reporting, practical details, and considered recommendations for curious readers.",
          buttonText: "Read the latest",
          href: "#latest",
          secondaryButtonText: "Explore topics",
          secondaryHref: "#topics",
        },
      },
      { type: BlockType.BLOG_GRID, content: { layout: "lead-mosaic", maxItems: 3 } },
      { type: BlockType.BLOG_GRID, content: { layout: "story-lane", maxItems: 4 } },
      { type: BlockType.FEATURES, content: { presentation: "theme" } },
      { type: BlockType.CTA, content: { presentation: "theme" } },
    ],
    preview: {
      eyebrow: "Editorial publication",
      title: "A clear home for stories",
      description: "Lead story, recent articles, topics, and a useful next step.",
      tone: "editorial",
    },
  },
  {
    id: "editorial-publication.article",
    patternId: "editorial-publication.article",
    name: "Editorial article",
    description: "Publish a long-form story with semantic formatting, linked media, tables, and embeds.",
    outcome: "A focused article body that inherits the active publication theme.",
    subject: "entry",
    category: "editorial",
    source: "pack",
    packId: "editorial-publication",
    templateId: "article-standard",
    collectionMatch: {
      presets: ["article"],
      terms: ["article", "articles", "post", "posts", "story", "stories", "guide", "guides"],
    },
    blocks: [{ type: BlockType.TEXT }],
    essentialFields: [
      {
        id: "excerpt",
        label: "Summary",
        type: "textarea",
        required: false,
        placeholder: "A short introduction for cards and search results.",
      },
      {
        id: "featuredImage",
        label: "Featured image",
        type: "image",
        required: false,
      },
    ],
    preview: {
      eyebrow: "Long-form story",
      title: "Write for reading, not a layout tool",
      description: "Semantic content, editorial rhythm, and publication metadata.",
      tone: "editorial",
    },
  },
  {
    id: "editorial-publication.topic-index",
    patternId: "editorial-publication.topic-index",
    name: "Topic landing page",
    description: "Introduce one editorial topic and surface its most useful stories.",
    outcome: "Topic introduction, article collection, and related topics.",
    subject: "page",
    category: "listing",
    source: "pack",
    packId: "editorial-publication",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "centered",
          eyebrow: "Topic",
          title: "Explore this subject in depth",
          subtitle: "A considered collection of reporting, practical guides, and first-hand experience.",
        },
      },
      { type: BlockType.BLOG_GRID, content: { presentation: "theme" } },
      { type: BlockType.CTA, content: { presentation: "theme" } },
    ],
    preview: {
      eyebrow: "Topic collection",
      title: "Give related stories a useful home",
      description: "Introduction, selected articles, and onward discovery.",
      tone: "editorial",
    },
  },
] as const satisfies readonly ContentBlueprintDefinition[];
