import assert from "node:assert/strict";
import { test } from "node:test";
import { createServer } from "node:http";
import { createRequire } from "node:module";
import { chromium } from "@playwright/test";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";

// Isolated in-memory fixture: no CMS login, content writes or database access.
test("preview controls: hover, boundaries, owning selection, keyboard, scroll, browse and empty state", async () => {
  const require = createRequire(import.meta.url);
  const esbuild = createRequire(require.resolve("tsx/package.json"))("esbuild");
  const bundle = await esbuild.build({ entryPoints: ["tests/fixtures/preview-overlay.tsx"], bundle: true, write: false, format: "iife", jsx: "automatic" });
  const css = await postcss([tailwind()]).process('@import "tailwindcss"; @source "./node_modules/@blockforge/preview/src"; @source "./tests/fixtures/preview-overlay.tsx";', { from: `${process.cwd()}/preview-fixture.css` });
  const server = createServer((_, response) => {
    response.setHeader("Content-Type", "text/html");
    response.end(`<!doctype html><html><head><style>${css.css}</style></head><body><div id="root"></div><script>${bundle.outputFiles[0].text}</script></body></html>`);
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage({ viewport: { width: 1000, height: 800 } });
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    const table = page.locator('[data-blockforge-block-id="table"]');
    await table.hover({ position: { x: 200, y: 130 } });
    const boundary = page.getByRole("button", { name: "Add section after Table" });
    await boundary.waitFor();
    const boundaryWidth = await boundary.locator("..").evaluate((node) => node.getBoundingClientRect().width);
    assert.equal(boundaryWidth, 800);
    await boundary.click();
    assert.deepEqual(await page.evaluate(() => window.previewEvents.at(-1)), { insert: { afterBlockId: "table" } });
    await page.getByText("Nested content").click();
    assert.deepEqual(await page.evaluate(() => window.previewEvents.at(-1)), { select: "table" });
    await page.getByRole("toolbar").waitFor();
    if (process.env.PREVIEW_SCREENSHOT_PATH) await page.screenshot({ path: process.env.PREVIEW_SCREENSHOT_PATH });
    assert.equal(await page.getByRole("button", { name: "Move section up" }).isDisabled(), true);
    const edit = page.getByRole("button", { name: "Edit section fields" });
    await edit.focus();
    await page.keyboard.press("ArrowRight");
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("aria-label")), "Move section down");
    await page.keyboard.press("Enter");
    assert.deepEqual(await page.evaluate(() => window.previewEvents.at(-1)), { id: "table", action: "move-down" });
    await page.getByRole("button", { name: "More section actions" }).click();
    await page.getByRole("button", { name: "Remove section", exact: true }).click();
    assert.deepEqual(await page.evaluate(() => window.previewEvents.at(-1)), { id: "table", action: "remove" });
    assert.equal(await page.evaluate(() => window.contentRenders), 1, "hover and selection must not re-render site content");
    await page.getByRole("button", { name: "Edit section fields" }).focus();
    await page.keyboard.press("Escape");
    assert.equal(await page.getByRole("toolbar").count(), 0);
    await table.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("toolbar").waitFor();
    await table.hover({ position: { x: 200, y: 130 } });
    const beforeScroll = await boundary.boundingBox();
    await page.evaluate(() => window.scrollBy(0, 60));
    await page.waitForFunction(() => document.querySelector('[aria-label="Add section after Table"]')?.getBoundingClientRect().top < 300);
    const afterScroll = await boundary.boundingBox();
    assert.equal(Math.round(beforeScroll.y - afterScroll.y), 60);
    await page.setViewportSize({ width: 800, height: 800 });
    await page.waitForFunction(() => document.querySelector('[aria-label="Add section after Table"]')?.parentElement?.getBoundingClientRect().width === 640);
    await page.locator('[data-blockforge-block-id="text"]').hover({ position: { x: 200, y: 130 } });
    assert.equal(await page.getByRole("button", { name: "Add section after Text" }).count(), 0, "offscreen boundaries must not be clamped to the viewport");
    await page.getByRole("button", { name: "Browse preview" }).click();
    assert.equal(await page.getByRole("toolbar").count(), 0);
    await page.getByRole("button", { name: "Website action" }).click();
    assert.equal(await page.evaluate(() => window.previewEvents.at(-1)), "website-click");
    const destinationOpened = page.context().waitForEvent("page");
    await page.getByRole("link", { name: "Website link" }).click();
    const destinationPage = await destinationOpened;
    await destinationPage.waitForURL("**/destination");
    assert.equal(new URL(page.url()).pathname, "/", "browsing must not replace the preview bridge");
    await destinationPage.close();
    await page.getByRole("button", { name: "Return to editing" }).click();
    await page.evaluate(() => window.emptyPreview());
    await page.getByRole("button", { name: "Add first section" }).click();
    assert.deepEqual(await page.evaluate(() => window.previewEvents.at(-1)), { insert: { atIndex: 0 } });
    assert.deepEqual(errors, []);
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
    await mobile.goto(`http://127.0.0.1:${server.address().port}`);
    await mobile.getByText("Nested content").tap();
    await mobile.getByRole("toolbar").waitFor();
    const toolbarBox = await mobile.getByRole("toolbar").boundingBox();
    assert.ok(toolbarBox.x >= 0 && toolbarBox.x + toolbarBox.width <= 390);
    await mobile.getByRole("button", { name: "More section actions" }).tap();
    await mobile.getByRole("button", { name: "Add before", exact: true }).tap();
    assert.deepEqual(await mobile.evaluate(() => window.previewEvents.at(-1)), { id: "table", action: "insert-before" });
  } finally {
    await browser?.close();
    await new Promise((resolve) => server.close(resolve));
  }
});
