import { BlockType, type ContentBlueprintDefinition } from "../../../types";

export const travelAgencyBlueprints = [
  {
    id: "travel-agency.homepage",
    patternId: "travel-agency.home",
    name: "Travel homepage",
    description: "Inspire visitors, introduce featured journeys, and create a direct route to enquiry.",
    outcome: "Hero, featured tour, journey categories, trust, and contact CTA.",
    subject: "page",
    category: "home",
    source: "pack",
    packId: "travel-agency",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "Selected journeys",
          title: "See the world from a different perspective",
          subtitle: "Carefully selected journeys combining memorable places, local stories, and thoughtful service.",
          buttonText: "Explore tours",
          href: "/tours/",
          secondaryButtonText: "Plan my trip",
          secondaryHref: "/contact/",
          bgImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=82&w=1800",
          imageAlt: "Great Wall winding across green mountains",
          imageCaption: "Travel Agency · Seasonal collection",
        },
      },
      { type: BlockType.TRAVEL_FEATURED_OFFER },
      { type: BlockType.TRAVEL_JOURNEY_GRID },
      { type: BlockType.TRAVEL_TRUST_STRIP },
      { type: BlockType.TRAVEL_CONTACT_CTA },
    ],
    preview: {
      eyebrow: "Travel agency",
      title: "Turn inspiration into an enquiry",
      description: "A complete agency homepage focused on discovery and trust.",
      tone: "editorial",
    },
  },
  {
    id: "travel-agency.catalogue",
    patternId: "travel-agency.tour-catalogue",
    name: "Tour catalogue",
    description: "Present the available tours clearly and guide visitors towards the right itinerary.",
    outcome: "Editorial introduction, tour catalogue, and enquiry CTA.",
    subject: "page",
    category: "listing",
    source: "pack",
    packId: "travel-agency",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "Tour collection",
          title: "Find the journey that fits",
          subtitle: "Compare destinations, durations, departures, and the details that matter before you enquire.",
          buttonText: "Browse journeys",
          href: "#tours",
          secondaryButtonText: "Ask for advice",
          secondaryHref: "/contact/",
          bgImage: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?auto=format&fit=crop&q=82&w=1800",
          imageAlt: "Traditional Chinese architecture beside a lake",
        },
      },
      {
        type: BlockType.TRAVEL_TOUR_CATALOGUE,
        content: { collectionId: "collection-tours" },
      },
      { type: BlockType.TRAVEL_CONTACT_CTA },
    ],
    preview: {
      eyebrow: "Tour collection",
      title: "Help travellers compare journeys",
      description: "A catalogue page that routes visitors into individual tours.",
      tone: "catalogue",
    },
  },
  {
    id: "travel-agency.tour-detail",
    patternId: "travel-agency.tour-detail",
    name: "Tour details",
    description: "Explain one tour with dates, prices, itinerary information, and an enquiry form.",
    outcome: "Overview, package, departures, programme, story, and enquiry.",
    subject: "entry",
    category: "detail",
    source: "pack",
    packId: "travel-agency",
    templateId: "landing-page",
    collectionMatch: {
      terms: ["tour", "tours", "trip", "journey"],
    },
    blocks: [
      {
        type: BlockType.TRAVEL_TOUR_OVERVIEW,
        content: {
          title: "{{title}}",
          summary: "{{fields.summary}}",
          image: "{{fields.heroImage}}",
          imageAlt: "{{fields.heroImageAlt}}",
        },
      },
      { type: BlockType.TRAVEL_TOUR_STORY },
      { type: BlockType.TRAVEL_SECTION_HEADING },
      { type: BlockType.TRAVEL_TOUR_PACKAGE },
      {
        type: BlockType.TRAVEL_TOUR_ENQUIRY,
        content: { collectionId: "{{collection.id}}" },
      },
    ],
    essentialFields: [
      {
        id: "summary",
        label: "Short summary",
        type: "textarea",
        required: true,
        placeholder: "What makes this journey memorable?",
      },
      {
        id: "heroImage",
        label: "Featured image",
        type: "image",
        required: true,
      },
    ],
    preview: {
      eyebrow: "Individual tour",
      title: "Everything needed to choose a journey",
      description: "A complete detail page designed to answer questions and generate enquiries.",
      tone: "editorial",
    },
  },
  {
    id: "travel-agency.enquiry",
    patternId: "travel-agency.enquiry",
    name: "Travel enquiry",
    description: "Collect the essential information needed to recommend or book a journey.",
    outcome: "Editorial introduction and a focused travel enquiry form.",
    subject: "page",
    category: "contact",
    source: "pack",
    packId: "travel-agency",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "Plan a journey",
          title: "Tell us where you want to go",
          subtitle: "Share the essentials and the travel team will help shape the right journey.",
          buttonText: "Start your enquiry",
          href: "#enquiry",
          secondaryButtonText: "Browse tours",
          secondaryHref: "/tours/",
          bgImage: "https://images.unsplash.com/photo-1529921879218-f99546d03a31?auto=format&fit=crop&q=82&w=1800",
          imageAlt: "Mountain landscape at sunrise",
        },
      },
      { type: BlockType.TRAVEL_TOUR_ENQUIRY },
    ],
    preview: {
      eyebrow: "Plan a journey",
      title: "Make it easy to ask for help",
      description: "A direct consultation page with only the information the travel team needs.",
      tone: "conversion",
    },
  },
] as const satisfies readonly ContentBlueprintDefinition[];
