import { BlockType, type ContentBlueprintDefinition } from "../../../types";

export const coreBlueprints = [
  {
    id: "core.blank-page",
    name: "Blank page",
    description: "Start with a clean page and add only the sections you need.",
    outcome: "A flexible page with no preselected layout.",
    subject: "page",
    category: "blank",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [],
    preview: {
      eyebrow: "Start from scratch",
      title: "A clean canvas",
      description: "Add sections after the page is created.",
      tone: "neutral",
    },
  },
  {
    id: "core.site-home",
    patternId: "core.home",
    name: "Website homepage",
    description: "Introduce the organisation, explain its value, add proof, and guide visitors forward.",
    outcome: "A complete, neutral homepage that adapts to the active theme.",
    subject: "page",
    category: "home",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "A clear introduction",
          title: "Make the value immediately understandable",
          subtitle: "Introduce the organisation in plain language, support the promise with evidence, and offer one useful next step.",
          buttonText: "Explore what we do",
          secondaryButtonText: "Start a conversation",
        },
      },
      { type: BlockType.LOGO_CLOUD },
      { type: BlockType.FEATURES },
      { type: BlockType.IMAGE_TEXT },
      { type: BlockType.TESTIMONIALS },
      { type: BlockType.CTA },
    ],
    preview: {
      eyebrow: "Complete website",
      title: "A coherent homepage",
      description: "Introduction, value, story, proof, and one clear next step.",
      tone: "conversion",
    },
  },
  {
    id: "core.about-page",
    patternId: "core.about",
    name: "About page",
    description: "Explain the organisation's story, approach, and evidence.",
    outcome: "An editorial story page with measurable proof and customer trust.",
    subject: "page",
    category: "editorial",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      { type: BlockType.HERO, content: { layout: "centered", eyebrow: "About us", title: "The story behind the work", subtitle: "Explain what the organisation believes, how it works, and why that matters to customers." } },
      { type: BlockType.IMAGE_TEXT, content: { layout: "theme" } },
      { type: BlockType.STATS },
      { type: BlockType.TESTIMONIALS, content: { presentation: "spotlight" } },
    ],
    preview: {
      eyebrow: "Organisation story",
      title: "Show who is behind the work",
      description: "Story, approach, evidence, and customer trust.",
      tone: "editorial",
    },
  },
  {
    id: "core.services-page",
    patternId: "core.services",
    name: "Services page",
    description: "Present capabilities, packages, and common questions clearly.",
    outcome: "A structured offer page with services, pricing, FAQs, and conversion CTA.",
    subject: "page",
    category: "listing",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      { type: BlockType.HERO, content: { layout: "theme", eyebrow: "Services", title: "Choose the support you need", subtitle: "Describe the available services and help visitors identify the right starting point." } },
      { type: BlockType.UI_CARD_GRID, content: { presentation: "theme", columns: "3" } },
      { type: BlockType.PRICING, content: { presentation: "theme" } },
      { type: BlockType.FAQ, content: { presentation: "theme" } },
      { type: BlockType.CTA },
    ],
    preview: {
      eyebrow: "Offers and capabilities",
      title: "A useful services page",
      description: "Services, packages, questions, and next step.",
      tone: "conversion",
    },
  },
  {
    id: "core.portfolio-page",
    patternId: "core.portfolio",
    name: "Work and proof page",
    description: "Use visual evidence and customer proof to make the work tangible.",
    outcome: "A visual portfolio page with gallery, proof, and CTA.",
    subject: "page",
    category: "listing",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      { type: BlockType.HERO, content: { layout: "centered", eyebrow: "Selected work", title: "See the work in context", subtitle: "Present representative outcomes, places, products, or projects without losing the active website identity." } },
      { type: BlockType.IMAGE_GALLERY, content: { presentation: "theme" } },
      { type: BlockType.TESTIMONIALS, content: { presentation: "theme" } },
      { type: BlockType.CTA },
    ],
    preview: {
      eyebrow: "Visual evidence",
      title: "Show the work clearly",
      description: "Gallery, customer proof, and a clear next step.",
      tone: "editorial",
    },
  },
  {
    id: "core.landing-page",
    patternId: "core.landing",
    name: "Landing page",
    description: "Introduce one clear offer with supporting benefits and a call to action.",
    outcome: "Hero, benefits, supporting content, and conversion CTA.",
    subject: "page",
    category: "landing",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "Focused campaign",
          title: "Present one clear idea",
          subtitle: "Explain why it matters, support it with proof, and guide visitors toward one obvious next step.",
          buttonText: "Get started",
          secondaryButtonText: "Learn more",
        },
      },
      { type: BlockType.FEATURES },
      { type: BlockType.IMAGE_TEXT },
      { type: BlockType.CTA },
    ],
    preview: {
      eyebrow: "Focused campaign",
      title: "Present one clear idea",
      description: "A balanced marketing page with an obvious next step.",
      tone: "conversion",
    },
  },
  {
    id: "core.contact-page",
    patternId: "core.contact",
    name: "Contact page",
    description: "Give visitors a clear way to ask a question or request a response.",
    outcome: "A focused introduction and contact form in the active site style.",
    subject: "page",
    category: "contact",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      { type: BlockType.HERO, content: { layout: "theme", eyebrow: "Contact", title: "Start a useful conversation", subtitle: "Set expectations clearly and make it easy for visitors to ask for the right help." } },
      { type: BlockType.CONTACT_FORM, content: { presentation: "theme" } },
    ],
    preview: {
      eyebrow: "Contact",
      title: "Start a conversation",
      description: "Simple contact information and an enquiry form.",
      tone: "conversion",
    },
  },
  {
    id: "core.flexible-story-page",
    patternId: "core.landing",
    name: "Flexible story page",
    description: "Combine a strong opening with mixed text, media, proof, and a clear next step.",
    outcome: "Theme hero, mixed-content composition, and conversion CTA.",
    subject: "page",
    category: "landing",
    source: "pack",
    packId: "core",
    templateId: "landing-page",
    blocks: [
      {
        type: BlockType.HERO,
        content: {
          layout: "theme",
          eyebrow: "A flexible story",
          title: "Build a page around the content",
          subtitle: "Choose the composition that fits the message while the active theme keeps every section connected.",
          buttonText: "Get started",
          secondaryButtonText: "Learn more",
        },
      },
      { type: BlockType.TWO_COLUMN },
      {
        type: BlockType.CTA,
        content: {
          presentation: "theme",
          eyebrow: "Next step",
          title: "Turn interest into action",
          subtitle: "Finish the story with one clear outcome.",
          buttonText: "Contact us",
          href: "/contact/",
        },
      },
    ],
    preview: {
      eyebrow: "Composable Core",
      title: "A flexible story in one visual system",
      description: "Mix different content types without leaving the active website theme.",
      tone: "editorial",
    },
  },
  {
    id: "core.standard-entry",
    name: "Standard entry",
    description:
      "Start a repeatable content entry with a clear title and editable body.",
    outcome: "A simple editorial entry that works with any content model.",
    subject: "entry",
    category: "editorial",
    source: "pack",
    packId: "core",
    templateId: "article-standard",
    blocks: [{ type: BlockType.TEXT }],
    preview: {
      eyebrow: "Repeatable content",
      title: "A clear editorial starting point",
      description:
        "Use model fields for structured data and the text section for the story.",
      tone: "neutral",
    },
  },
] as const satisfies readonly ContentBlueprintDefinition[];
