/* Generated by scripts/generate-client-extension-registry.mjs. */
import type { ComponentType } from "react";
import ExtensionView0 from "./../client-extensions/SkooveLearningPathHero";

export const generatedClientExtensionViews = {
  "CUSTOM:SKOOVE_LEARNING_PATH_HERO": ExtensionView0,
} as Record<string, ComponentType<any>>;
