/* Generated by scripts/generate-next-block-registry.mjs. */
import type { ComponentType } from "react";
import { BlockType } from "../../types";
import definition0 from "./blog-grid/definition";
import { BlogGridView } from "./blog-grid/View";
import { Preview as Preview0 } from "./blog-grid/Preview";
import definition1 from "./contact-form/definition";
import { ContactFormView } from "./contact-form/View";
import { Preview as Preview1 } from "./contact-form/Preview";
import definition2 from "./cta/definition";
import { CtaView } from "./cta/View";
import { Preview as Preview2 } from "./cta/Preview";
import definition3 from "./faq/definition";
import { FaqView } from "./faq/View";
import { Preview as Preview3 } from "./faq/Preview";
import definition4 from "./feature-bento/definition";
import { FeatureBentoView } from "./feature-bento/View";
import { Preview as Preview4 } from "./feature-bento/Preview";
import definition5 from "./features/definition";
import { FeaturesView } from "./features/View";
import { Preview as Preview5 } from "./features/Preview";
import definition6 from "./hero/definition";
import { HeroView } from "./hero/View";
import { Preview as Preview6 } from "./hero/Preview";
import definition7 from "./image-gallery/definition";
import { ImageGalleryView } from "./image-gallery/View";
import { Preview as Preview7 } from "./image-gallery/Preview";
import definition8 from "./image-text/definition";
import { ImageTextView } from "./image-text/View";
import { Preview as Preview8 } from "./image-text/Preview";
import definition9 from "./logo-cloud/definition";
import { LogoCloudView } from "./logo-cloud/View";
import { Preview as Preview9 } from "./logo-cloud/Preview";
import definition10 from "./media/definition";
import { MediaView } from "./media/View";
import { Preview as Preview10 } from "./media/Preview";
import definition11 from "./newsletter-signup/definition";
import { NewsletterSignupView } from "./newsletter-signup/View";
import { Preview as Preview11 } from "./newsletter-signup/Preview";
import definition12 from "./pricing/definition";
import { PricingView } from "./pricing/View";
import { Preview as Preview12 } from "./pricing/Preview";
import definition13 from "./../packs/editorial-publication/blocks/publication-gateway-carousel/definition";
import { PublicationGatewayCarouselView } from "./../packs/editorial-publication/blocks/publication-gateway-carousel/View";
import { Preview as Preview13 } from "./../packs/editorial-publication/blocks/publication-gateway-carousel/Preview";
import definition14 from "./../packs/editorial-publication/blocks/publication-hero/definition";
import { PublicationHeroView } from "./../packs/editorial-publication/blocks/publication-hero/View";
import { Preview as Preview14 } from "./../packs/editorial-publication/blocks/publication-hero/Preview";
import definition15 from "./rental-about/definition";
import { RentalAboutView } from "./rental-about/View";
import { Preview as Preview15 } from "./rental-about/Preview";
import definition16 from "./rental-cta/definition";
import { RentalCtaView } from "./rental-cta/View";
import { Preview as Preview16 } from "./rental-cta/Preview";
import definition17 from "./rental-features/definition";
import { RentalFeaturesView } from "./rental-features/View";
import { Preview as Preview17 } from "./rental-features/Preview";
import definition18 from "./rental-hero/definition";
import { RentalHeroView } from "./rental-hero/View";
import { Preview as Preview18 } from "./rental-hero/Preview";
import definition19 from "./rental-image-text/definition";
import { RentalImageTextView } from "./rental-image-text/View";
import { Preview as Preview19 } from "./rental-image-text/Preview";
import definition20 from "./rental-problem/definition";
import { RentalProblemView } from "./rental-problem/View";
import { Preview as Preview20 } from "./rental-problem/Preview";
import definition21 from "./shared-block/definition";
import { SharedBlockView } from "./shared-block/View";
import { Preview as Preview21 } from "./shared-block/Preview";
import definition22 from "./stats/definition";
import { StatsView } from "./stats/View";
import { Preview as Preview22 } from "./stats/Preview";
import definition23 from "./table/definition";
import { TableView } from "./table/View";
import { Preview as Preview23 } from "./table/Preview";
import definition24 from "./testimonials/definition";
import { TestimonialsView } from "./testimonials/View";
import { Preview as Preview24 } from "./testimonials/Preview";
import definition25 from "./text/definition";
import { TextView } from "./text/View";
import { Preview as Preview25 } from "./text/Preview";
import definition26 from "./../packs/travel-agency/blocks/viet-contact-cta/definition";
import { VietContactCtaView } from "./../packs/travel-agency/blocks/viet-contact-cta/View";
import { Preview as Preview26 } from "./../packs/travel-agency/blocks/viet-contact-cta/Preview";
import definition27 from "./../packs/travel-agency/blocks/viet-departure-schedule/definition";
import { VietDepartureScheduleView } from "./../packs/travel-agency/blocks/viet-departure-schedule/View";
import { Preview as Preview27 } from "./../packs/travel-agency/blocks/viet-departure-schedule/Preview";
import definition28 from "./../packs/travel-agency/blocks/viet-editorial-hero/definition";
import { VietEditorialHeroView } from "./../packs/travel-agency/blocks/viet-editorial-hero/View";
import { Preview as Preview28 } from "./../packs/travel-agency/blocks/viet-editorial-hero/Preview";
import definition29 from "./../packs/travel-agency/blocks/viet-featured-offer/definition";
import { VietFeaturedOfferView } from "./../packs/travel-agency/blocks/viet-featured-offer/View";
import { Preview as Preview29 } from "./../packs/travel-agency/blocks/viet-featured-offer/Preview";
import definition30 from "./../packs/travel-agency/blocks/viet-journey-grid/definition";
import { VietJourneyGridView } from "./../packs/travel-agency/blocks/viet-journey-grid/View";
import { Preview as Preview30 } from "./../packs/travel-agency/blocks/viet-journey-grid/Preview";
import definition31 from "./../packs/travel-agency/blocks/viet-programme-link/definition";
import { VietProgrammeLinkView } from "./../packs/travel-agency/blocks/viet-programme-link/View";
import { Preview as Preview31 } from "./../packs/travel-agency/blocks/viet-programme-link/Preview";
import definition32 from "./../packs/travel-agency/blocks/viet-section-heading/definition";
import { VietSectionHeadingView } from "./../packs/travel-agency/blocks/viet-section-heading/View";
import { Preview as Preview32 } from "./../packs/travel-agency/blocks/viet-section-heading/Preview";
import definition33 from "./../packs/travel-agency/blocks/viet-tour-catalogue/definition";
import { VietTourCatalogueView } from "./../packs/travel-agency/blocks/viet-tour-catalogue/View";
import { Preview as Preview33 } from "./../packs/travel-agency/blocks/viet-tour-catalogue/Preview";
import definition34 from "./../packs/travel-agency/blocks/viet-tour-enquiry/definition";
import { VietTourEnquiryView } from "./../packs/travel-agency/blocks/viet-tour-enquiry/View";
import { Preview as Preview34 } from "./../packs/travel-agency/blocks/viet-tour-enquiry/Preview";
import definition35 from "./../packs/travel-agency/blocks/viet-tour-overview/definition";
import { VietTourOverviewView } from "./../packs/travel-agency/blocks/viet-tour-overview/View";
import { Preview as Preview35 } from "./../packs/travel-agency/blocks/viet-tour-overview/Preview";
import definition36 from "./../packs/travel-agency/blocks/viet-tour-package/definition";
import { VietTourPackageView } from "./../packs/travel-agency/blocks/viet-tour-package/View";
import { Preview as Preview36 } from "./../packs/travel-agency/blocks/viet-tour-package/Preview";
import definition37 from "./../packs/travel-agency/blocks/viet-tour-story/definition";
import { VietTourStoryView } from "./../packs/travel-agency/blocks/viet-tour-story/View";
import { Preview as Preview37 } from "./../packs/travel-agency/blocks/viet-tour-story/Preview";
import definition38 from "./../packs/travel-agency/blocks/viet-trust-strip/definition";
import { VietTrustStripView } from "./../packs/travel-agency/blocks/viet-trust-strip/View";
import { Preview as Preview38 } from "./../packs/travel-agency/blocks/viet-trust-strip/Preview";
import definition39 from "./two-column/definition";
import { TwoColumnView } from "./two-column/View";
import { Preview as Preview39 } from "./two-column/Preview";
import definition40 from "./ui-accordion/definition";
import { UiAccordionView } from "./ui-accordion/View";
import { Preview as Preview40 } from "./ui-accordion/Preview";
import definition41 from "./ui-button-cta/definition";
import { UiButtonCtaView } from "./ui-button-cta/View";
import { Preview as Preview41 } from "./ui-button-cta/Preview";
import definition42 from "./ui-card-grid/definition";
import { UiCardGridView } from "./ui-card-grid/View";
import { Preview as Preview42 } from "./ui-card-grid/Preview";
import definition43 from "./ui-tabs/definition";
import { UiTabsView } from "./ui-tabs/View";
import { Preview as Preview43 } from "./ui-tabs/Preview";
import definition44 from "./video-embed/definition";
import { VideoEmbedView } from "./video-embed/View";
import { Preview as Preview44 } from "./video-embed/Preview";

export const nextBlockEntries = [
  { definition: definition0, folder: "blog-grid", moduleRoot: "./blog-grid" },
  { definition: definition1, folder: "contact-form", moduleRoot: "./contact-form" },
  { definition: definition2, folder: "cta", moduleRoot: "./cta" },
  { definition: definition3, folder: "faq", moduleRoot: "./faq" },
  { definition: definition4, folder: "feature-bento", moduleRoot: "./feature-bento" },
  { definition: definition5, folder: "features", moduleRoot: "./features" },
  { definition: definition6, folder: "hero", moduleRoot: "./hero" },
  { definition: definition7, folder: "image-gallery", moduleRoot: "./image-gallery" },
  { definition: definition8, folder: "image-text", moduleRoot: "./image-text" },
  { definition: definition9, folder: "logo-cloud", moduleRoot: "./logo-cloud" },
  { definition: definition10, folder: "media", moduleRoot: "./media" },
  { definition: definition11, folder: "newsletter-signup", moduleRoot: "./newsletter-signup" },
  { definition: definition12, folder: "pricing", moduleRoot: "./pricing" },
  { definition: definition13, folder: "publication-gateway-carousel", moduleRoot: "./../packs/editorial-publication/blocks/publication-gateway-carousel" },
  { definition: definition14, folder: "publication-hero", moduleRoot: "./../packs/editorial-publication/blocks/publication-hero" },
  { definition: definition15, folder: "rental-about", moduleRoot: "./rental-about" },
  { definition: definition16, folder: "rental-cta", moduleRoot: "./rental-cta" },
  { definition: definition17, folder: "rental-features", moduleRoot: "./rental-features" },
  { definition: definition18, folder: "rental-hero", moduleRoot: "./rental-hero" },
  { definition: definition19, folder: "rental-image-text", moduleRoot: "./rental-image-text" },
  { definition: definition20, folder: "rental-problem", moduleRoot: "./rental-problem" },
  { definition: definition21, folder: "shared-block", moduleRoot: "./shared-block" },
  { definition: definition22, folder: "stats", moduleRoot: "./stats" },
  { definition: definition23, folder: "table", moduleRoot: "./table" },
  { definition: definition24, folder: "testimonials", moduleRoot: "./testimonials" },
  { definition: definition25, folder: "text", moduleRoot: "./text" },
  { definition: definition26, folder: "viet-contact-cta", moduleRoot: "./../packs/travel-agency/blocks/viet-contact-cta" },
  { definition: definition27, folder: "viet-departure-schedule", moduleRoot: "./../packs/travel-agency/blocks/viet-departure-schedule" },
  { definition: definition28, folder: "viet-editorial-hero", moduleRoot: "./../packs/travel-agency/blocks/viet-editorial-hero" },
  { definition: definition29, folder: "viet-featured-offer", moduleRoot: "./../packs/travel-agency/blocks/viet-featured-offer" },
  { definition: definition30, folder: "viet-journey-grid", moduleRoot: "./../packs/travel-agency/blocks/viet-journey-grid" },
  { definition: definition31, folder: "viet-programme-link", moduleRoot: "./../packs/travel-agency/blocks/viet-programme-link" },
  { definition: definition32, folder: "viet-section-heading", moduleRoot: "./../packs/travel-agency/blocks/viet-section-heading" },
  { definition: definition33, folder: "viet-tour-catalogue", moduleRoot: "./../packs/travel-agency/blocks/viet-tour-catalogue" },
  { definition: definition34, folder: "viet-tour-enquiry", moduleRoot: "./../packs/travel-agency/blocks/viet-tour-enquiry" },
  { definition: definition35, folder: "viet-tour-overview", moduleRoot: "./../packs/travel-agency/blocks/viet-tour-overview" },
  { definition: definition36, folder: "viet-tour-package", moduleRoot: "./../packs/travel-agency/blocks/viet-tour-package" },
  { definition: definition37, folder: "viet-tour-story", moduleRoot: "./../packs/travel-agency/blocks/viet-tour-story" },
  { definition: definition38, folder: "viet-trust-strip", moduleRoot: "./../packs/travel-agency/blocks/viet-trust-strip" },
  { definition: definition39, folder: "two-column", moduleRoot: "./two-column" },
  { definition: definition40, folder: "ui-accordion", moduleRoot: "./ui-accordion" },
  { definition: definition41, folder: "ui-button-cta", moduleRoot: "./ui-button-cta" },
  { definition: definition42, folder: "ui-card-grid", moduleRoot: "./ui-card-grid" },
  { definition: definition43, folder: "ui-tabs", moduleRoot: "./ui-tabs" },
  { definition: definition44, folder: "video-embed", moduleRoot: "./video-embed" },
] as const;

export const nextBlockViews = {
  [BlockType.BLOG_GRID]: BlogGridView,
  [BlockType.CONTACT_FORM]: ContactFormView,
  [BlockType.CTA]: CtaView,
  [BlockType.FAQ]: FaqView,
  [BlockType.FEATURE_BENTO]: FeatureBentoView,
  [BlockType.FEATURES]: FeaturesView,
  [BlockType.HERO]: HeroView,
  [BlockType.IMAGE_GALLERY]: ImageGalleryView,
  [BlockType.IMAGE_TEXT]: ImageTextView,
  [BlockType.LOGO_CLOUD]: LogoCloudView,
  [BlockType.MEDIA]: MediaView,
  [BlockType.NEWSLETTER_SIGNUP]: NewsletterSignupView,
  [BlockType.PRICING]: PricingView,
  [BlockType.PUBLICATION_GATEWAY_CAROUSEL]: PublicationGatewayCarouselView,
  [BlockType.PUBLICATION_HERO]: PublicationHeroView,
  [BlockType.RENTAL_ABOUT]: RentalAboutView,
  [BlockType.RENTAL_CTA]: RentalCtaView,
  [BlockType.RENTAL_FEATURES]: RentalFeaturesView,
  [BlockType.RENTAL_HERO]: RentalHeroView,
  [BlockType.RENTAL_IMAGE_TEXT]: RentalImageTextView,
  [BlockType.RENTAL_PROBLEM]: RentalProblemView,
  [BlockType.SHARED_BLOCK]: SharedBlockView,
  [BlockType.STATS]: StatsView,
  [BlockType.TABLE]: TableView,
  [BlockType.TESTIMONIALS]: TestimonialsView,
  [BlockType.TEXT]: TextView,
  [BlockType.TRAVEL_CONTACT_CTA]: VietContactCtaView,
  [BlockType.TRAVEL_DEPARTURE_SCHEDULE]: VietDepartureScheduleView,
  [BlockType.TRAVEL_EDITORIAL_HERO]: VietEditorialHeroView,
  [BlockType.TRAVEL_FEATURED_OFFER]: VietFeaturedOfferView,
  [BlockType.TRAVEL_JOURNEY_GRID]: VietJourneyGridView,
  [BlockType.TRAVEL_PROGRAMME_LINK]: VietProgrammeLinkView,
  [BlockType.TRAVEL_SECTION_HEADING]: VietSectionHeadingView,
  [BlockType.TRAVEL_TOUR_CATALOGUE]: VietTourCatalogueView,
  [BlockType.TRAVEL_TOUR_ENQUIRY]: VietTourEnquiryView,
  [BlockType.TRAVEL_TOUR_OVERVIEW]: VietTourOverviewView,
  [BlockType.TRAVEL_TOUR_PACKAGE]: VietTourPackageView,
  [BlockType.TRAVEL_TOUR_STORY]: VietTourStoryView,
  [BlockType.TRAVEL_TRUST_STRIP]: VietTrustStripView,
  [BlockType.TWO_COLUMN]: TwoColumnView,
  [BlockType.UI_ACCORDION]: UiAccordionView,
  [BlockType.UI_BUTTON_CTA]: UiButtonCtaView,
  [BlockType.UI_CARD_GRID]: UiCardGridView,
  [BlockType.UI_TABS]: UiTabsView,
  [BlockType.VIDEO_EMBED]: VideoEmbedView,
} as unknown as Record<BlockType, ComponentType<any>>;

export const nextBlockPreviews = {
  [BlockType.BLOG_GRID]: Preview0,
  [BlockType.CONTACT_FORM]: Preview1,
  [BlockType.CTA]: Preview2,
  [BlockType.FAQ]: Preview3,
  [BlockType.FEATURE_BENTO]: Preview4,
  [BlockType.FEATURES]: Preview5,
  [BlockType.HERO]: Preview6,
  [BlockType.IMAGE_GALLERY]: Preview7,
  [BlockType.IMAGE_TEXT]: Preview8,
  [BlockType.LOGO_CLOUD]: Preview9,
  [BlockType.MEDIA]: Preview10,
  [BlockType.NEWSLETTER_SIGNUP]: Preview11,
  [BlockType.PRICING]: Preview12,
  [BlockType.PUBLICATION_GATEWAY_CAROUSEL]: Preview13,
  [BlockType.PUBLICATION_HERO]: Preview14,
  [BlockType.RENTAL_ABOUT]: Preview15,
  [BlockType.RENTAL_CTA]: Preview16,
  [BlockType.RENTAL_FEATURES]: Preview17,
  [BlockType.RENTAL_HERO]: Preview18,
  [BlockType.RENTAL_IMAGE_TEXT]: Preview19,
  [BlockType.RENTAL_PROBLEM]: Preview20,
  [BlockType.SHARED_BLOCK]: Preview21,
  [BlockType.STATS]: Preview22,
  [BlockType.TABLE]: Preview23,
  [BlockType.TESTIMONIALS]: Preview24,
  [BlockType.TEXT]: Preview25,
  [BlockType.TRAVEL_CONTACT_CTA]: Preview26,
  [BlockType.TRAVEL_DEPARTURE_SCHEDULE]: Preview27,
  [BlockType.TRAVEL_EDITORIAL_HERO]: Preview28,
  [BlockType.TRAVEL_FEATURED_OFFER]: Preview29,
  [BlockType.TRAVEL_JOURNEY_GRID]: Preview30,
  [BlockType.TRAVEL_PROGRAMME_LINK]: Preview31,
  [BlockType.TRAVEL_SECTION_HEADING]: Preview32,
  [BlockType.TRAVEL_TOUR_CATALOGUE]: Preview33,
  [BlockType.TRAVEL_TOUR_ENQUIRY]: Preview34,
  [BlockType.TRAVEL_TOUR_OVERVIEW]: Preview35,
  [BlockType.TRAVEL_TOUR_PACKAGE]: Preview36,
  [BlockType.TRAVEL_TOUR_STORY]: Preview37,
  [BlockType.TRAVEL_TRUST_STRIP]: Preview38,
  [BlockType.TWO_COLUMN]: Preview39,
  [BlockType.UI_ACCORDION]: Preview40,
  [BlockType.UI_BUTTON_CTA]: Preview41,
  [BlockType.UI_CARD_GRID]: Preview42,
  [BlockType.UI_TABS]: Preview43,
  [BlockType.VIDEO_EMBED]: Preview44,
} as unknown as Record<BlockType, ComponentType<any>>;
