import { z } from "zod";
import { BlockType } from "../../../../../types";
import { optionalString, type BlockDefinition } from "../../../../blocks/types";

const navigationLinkSchema = z.object({ id: optionalString, label: z.string(), href: z.string() }).passthrough();

export const vietTourCatalogueBlock = {
  type: BlockType.TRAVEL_TOUR_CATALOGUE, label: "Tour Catalogue", shortLabel: "TC", category: "Travel Agency", order: 106,
  defaultContent: { sectionId: "", collectionId: "collection-tours", locale: "en-US", currency: "USD", contactPriceLabel: "Contact us", eyebrow: "Journey collection", title: "Tours available now", body: "Selected journeys updated throughout the season.", emptyMessage: "No tours have been published yet.", durationLabel: "Duration", routeLabel: "Transport", priceLabel: "From", detailLabel: "Details", featuredOnly: false, categoryId: "", limit: 0, navigationLinks: [] },
  schema: z.object({ sectionId: optionalString, collectionId: optionalString, locale: optionalString, currency: optionalString, contactPriceLabel: optionalString, eyebrow: optionalString, title: optionalString, body: optionalString, emptyMessage: optionalString, durationLabel: optionalString, routeLabel: optionalString, priceLabel: optionalString, detailLabel: optionalString, featuredOnly: z.boolean().optional(), categoryId: optionalString, limit: z.coerce.number().min(0).max(100).optional(), navigationLinks: z.array(navigationLinkSchema).optional() }).passthrough(),
  fields: [{ id: "sectionId", label: "Section Anchor ID", type: "text" }, { id: "collectionId", label: "Tour Collection ID", type: "text" }, { id: "locale", label: "Price Locale", type: "text" }, { id: "currency", label: "Currency Code", type: "text" }, { id: "contactPriceLabel", label: "Missing Price Label", type: "text" }, { id: "eyebrow", label: "Eyebrow", type: "text" }, { id: "title", label: "Title", type: "text" }, { id: "body", label: "Body", type: "textarea", rows: 4 }, { id: "emptyMessage", label: "Empty Message", type: "textarea", rows: 2 }, { id: "durationLabel", label: "Duration Label", type: "text" }, { id: "routeLabel", label: "Route Label", type: "text" }, { id: "priceLabel", label: "Price Label", type: "text" }, { id: "detailLabel", label: "Detail Link Label", type: "text" }, { id: "featuredOnly", label: "Featured Tours Only", type: "boolean" }, { id: "categoryId", label: "Category ID", type: "text" }, { id: "limit", label: "Maximum Tours", type: "number" }, { id: "navigationLinks", label: "Group Navigation", type: "repeater", addLabel: "Add Group Link", defaultItem: { id: "", label: "Journey group", href: "#" }, fields: [{ id: "id", label: "ID", type: "text" }, { id: "label", label: "Label", type: "text" }, { id: "href", label: "Anchor Link", type: "text" }] }],
} satisfies BlockDefinition;
export default vietTourCatalogueBlock;
